import {
  _ as resolveGroupDmAllow,
  a as normalizeDiscordSlug,
  c as resolveDiscordChannelConfigWithFallback,
  d as resolveDiscordGuildEntry,
  g as resolveDiscordShouldRequireMention,
  n as isDiscordGroupAllowedByPolicy,
  r as normalizeDiscordAllowList,
  s as resolveDiscordChannelConfig,
  t as allowListMatches,
  u as resolveDiscordCommandAuthorized,
  v as shouldEmitDiscordReactionNotification,
} from "../../allow-list-Jocmm0YN.js";
import {
  n as collectDiscordAuditChannelIds,
  t as auditDiscordChannelPermissions,
} from "../../audit-DvS3Uo4-.js";
import { t as discordMessageActions } from "../../channel-actions-D7C5gIx0.js";
import {
  n as listDiscordDirectoryPeersLive,
  t as listDiscordDirectoryGroupsLive,
} from "../../directory-live-BeAeN92S.js";
import {
  a as clearPresences,
  c as setPresence,
  i as unregisterGateway,
  n as getGateway,
  o as getPresence,
  r as registerGateway,
  s as presenceCacheSize,
  t as clearGateways,
} from "../../gateway-registry-Ph3ZXtQV.js";
import { t as createDiscordMessageHandler } from "../../message-handler-CDziEsnH.js";
import { i as buildDiscordMediaPayload } from "../../message-utils-DmLq_iNk.js";
import { t as resolveDiscordOutboundSessionRoute } from "../../outbound-session-route-CITZVYyj.js";
import {
  a as resolveDiscordPrivilegedIntentsFromFlags,
  i as probeDiscord,
  n as fetchDiscordApplicationSummary,
  r as parseApplicationIdFromToken,
  t as fetchDiscordApplicationId,
} from "../../probe-C9hRGOwK.js";
import {
  a as createDiscordNativeCommand,
  i as waitForDiscordGatewayPluginRegistration,
  n as createDiscordGatewayPlugin,
  o as registerDiscordListener,
  r as resolveDiscordGatewayIntents,
  t as monitorDiscordProvider,
} from "../../provider-CqBiOSvx.js";
import { t as resolveDiscordChannelAllowlist } from "../../resolve-channels-DXObv-GJ.js";
import { t as resolveDiscordUserAllowlist } from "../../resolve-users-l3avRb8a.js";
import { r as setDiscordRuntime } from "../../runtime-BuudSymP.js";
import {
  a as readDiscordChannelCreateParams,
  c as readDiscordParentIdParam,
  i as requiredGuildPermissionForModerationAction,
  n as isDiscordModerationAction,
  o as readDiscordChannelEditParams,
  r as readDiscordModerationCommand,
  s as readDiscordChannelMoveParams,
  t as handleDiscordAction,
} from "../../runtime-CSI7M7P5.js";
import {
  A as resolveEventCoverImage,
  B as setChannelPermissionDiscord,
  C as fetchMemberInfoDiscord,
  D as listGuildChannelsDiscord,
  E as kickMemberDiscord,
  F as createChannelDiscord,
  I as deleteChannelDiscord,
  L as editChannelDiscord,
  M as listGuildEmojisDiscord,
  N as uploadEmojiDiscord,
  O as listScheduledEventsDiscord,
  P as uploadStickerDiscord,
  R as moveChannelDiscord,
  S as fetchChannelInfoDiscord,
  T as fetchVoiceStatusDiscord,
  _ as searchMessagesDiscord,
  a as sendTypingDiscord,
  b as banMemberDiscord,
  d as editMessageDiscord,
  f as fetchMessageDiscord,
  g as readMessagesDiscord,
  h as pinMessageDiscord,
  i as removeReactionDiscord,
  j as timeoutMemberDiscord,
  k as removeRoleDiscord,
  l as createThreadDiscord,
  m as listThreadsDiscord,
  n as reactMessageDiscord,
  o as sendVoiceMessageDiscord,
  p as listPinsDiscord,
  r as removeOwnReactionsDiscord,
  s as sendWebhookMessageDiscord,
  t as fetchReactionsDiscord,
  u as deleteMessageDiscord,
  v as unpinMessageDiscord,
  w as fetchRoleInfoDiscord,
  x as createScheduledEventDiscord,
  y as addRoleDiscord,
  z as removeChannelPermissionDiscord,
} from "../../send-MjDHAxf5.js";
import {
  n as registerBuiltDiscordComponentMessage,
  r as sendDiscordComponentMessage,
  t as editDiscordComponentMessage,
} from "../../send.components-Bn4ZeGKu.js";
import {
  n as sendPollDiscord,
  r as sendStickerDiscord,
  t as sendMessageDiscord,
} from "../../send.outbound-8Xjee9fn.js";
import {
  C as DiscordSendError,
  D as hasAllGuildPermissionsDiscord,
  E as fetchMemberGuildPermissionsDiscord,
  O as hasAnyGuildPermissionDiscord,
  T as fetchChannelPermissionsDiscord,
} from "../../send.shared-DW2ozbKR.js";
import {
  a as unbindThreadBindingsBySessionKey,
  i as reconcileAcpThreadBindingsOnStartup,
  n as listThreadBindingsBySessionKey,
  o as resolveDiscordThreadBindingIdleTimeoutMs,
  r as listThreadBindingsForAccount,
  s as resolveDiscordThreadBindingMaxAgeMs,
  t as autoBindSpawnedDiscordSubagent,
} from "../../thread-bindings-DLL_GW9B.js";
import {
  i as resolveThreadBindingThreadName,
  r as resolveThreadBindingIntroText,
  t as formatThreadBindingDurationLabel,
} from "../../thread-bindings-messages-DyjCuJxS.js";
import { d as resolveThreadBindingsEnabled } from "../../thread-bindings-policy-CD0S48SB.js";
import {
  l as resolveThreadBindingPersona,
  u as resolveThreadBindingPersonaFromRecord,
} from "../../thread-bindings.discord-api-P_KqfyL6.js";
import "../../runtime-api.actions-DNMJnXcC.js";
import {
  i as getThreadBindingManager,
  n as createNoopThreadBindingManager,
  r as createThreadBindingManager,
  t as __testing,
} from "../../thread-bindings.manager-BVIWoDc5.js";
import "../../runtime-api.lookup-Ca95CJEc.js";
import {
  n as setThreadBindingMaxAgeBySessionKey,
  t as setThreadBindingIdleTimeoutBySessionKey,
} from "../../thread-bindings.session-updates-tIGgWAaH.js";
import {
  C as resolveThreadBindingMaxAgeMs,
  S as resolveThreadBindingMaxAgeExpiresAt,
  b as resolveThreadBindingIdleTimeoutMs,
  l as isRecentlyUnboundThreadWebhookMessage,
  x as resolveThreadBindingInactivityExpiresAt,
} from "../../thread-bindings.state-CKQgXU5N.js";
import {
  a as resolveDiscordReplyTarget,
  l as sanitizeDiscordThreadName,
} from "../../threading-BVg6zz2u.js";
import {
  a as mergeAbortSignals,
  i as DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
  n as DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS,
  r as DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  t as DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS,
} from "../../timeouts-B4h4bmv9.js";
import "../../runtime-api.monitor-DZVBoRDY.js";
import "../../runtime-api.send-BjsFXsND.js";
import "../../runtime-api.threads-BkZN8DfQ.js";
export {
  DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS,
  DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS,
  DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
  DiscordSendError,
  __testing,
  addRoleDiscord,
  allowListMatches,
  auditDiscordChannelPermissions,
  autoBindSpawnedDiscordSubagent,
  banMemberDiscord,
  buildDiscordMediaPayload,
  clearGateways,
  clearPresences,
  collectDiscordAuditChannelIds,
  createChannelDiscord,
  createDiscordGatewayPlugin,
  createDiscordMessageHandler,
  createDiscordNativeCommand,
  createNoopThreadBindingManager,
  createScheduledEventDiscord,
  createThreadBindingManager,
  createThreadDiscord,
  deleteChannelDiscord,
  deleteMessageDiscord,
  discordMessageActions,
  editChannelDiscord,
  editDiscordComponentMessage,
  editMessageDiscord,
  fetchChannelInfoDiscord,
  fetchChannelPermissionsDiscord,
  fetchDiscordApplicationId,
  fetchDiscordApplicationSummary,
  fetchMemberGuildPermissionsDiscord,
  fetchMemberInfoDiscord,
  fetchMessageDiscord,
  fetchReactionsDiscord,
  fetchRoleInfoDiscord,
  fetchVoiceStatusDiscord,
  formatThreadBindingDurationLabel,
  getGateway,
  getPresence,
  getThreadBindingManager,
  handleDiscordAction,
  hasAllGuildPermissionsDiscord,
  hasAnyGuildPermissionDiscord,
  isDiscordGroupAllowedByPolicy,
  isDiscordModerationAction,
  isRecentlyUnboundThreadWebhookMessage,
  kickMemberDiscord,
  listDiscordDirectoryGroupsLive,
  listDiscordDirectoryPeersLive,
  listGuildChannelsDiscord,
  listGuildEmojisDiscord,
  listPinsDiscord,
  listScheduledEventsDiscord,
  listThreadBindingsBySessionKey,
  listThreadBindingsForAccount,
  listThreadsDiscord,
  mergeAbortSignals,
  monitorDiscordProvider,
  moveChannelDiscord,
  normalizeDiscordAllowList,
  normalizeDiscordSlug,
  parseApplicationIdFromToken,
  pinMessageDiscord,
  presenceCacheSize,
  probeDiscord,
  reactMessageDiscord,
  readDiscordChannelCreateParams,
  readDiscordChannelEditParams,
  readDiscordChannelMoveParams,
  readDiscordModerationCommand,
  readDiscordParentIdParam,
  readMessagesDiscord,
  reconcileAcpThreadBindingsOnStartup,
  registerBuiltDiscordComponentMessage,
  registerDiscordListener,
  registerGateway,
  removeChannelPermissionDiscord,
  removeOwnReactionsDiscord,
  removeReactionDiscord,
  removeRoleDiscord,
  requiredGuildPermissionForModerationAction,
  resolveDiscordChannelAllowlist,
  resolveDiscordChannelConfig,
  resolveDiscordChannelConfigWithFallback,
  resolveDiscordCommandAuthorized,
  resolveDiscordGatewayIntents,
  resolveDiscordGuildEntry,
  resolveDiscordOutboundSessionRoute,
  resolveDiscordPrivilegedIntentsFromFlags,
  resolveDiscordReplyTarget,
  resolveDiscordShouldRequireMention,
  resolveDiscordThreadBindingIdleTimeoutMs,
  resolveDiscordThreadBindingMaxAgeMs,
  resolveDiscordUserAllowlist,
  resolveEventCoverImage,
  resolveGroupDmAllow,
  resolveThreadBindingIdleTimeoutMs,
  resolveThreadBindingInactivityExpiresAt,
  resolveThreadBindingIntroText,
  resolveThreadBindingMaxAgeExpiresAt,
  resolveThreadBindingMaxAgeMs,
  resolveThreadBindingPersona,
  resolveThreadBindingPersonaFromRecord,
  resolveThreadBindingThreadName,
  resolveThreadBindingsEnabled,
  sanitizeDiscordThreadName,
  searchMessagesDiscord,
  sendDiscordComponentMessage,
  sendMessageDiscord,
  sendPollDiscord,
  sendStickerDiscord,
  sendTypingDiscord,
  sendVoiceMessageDiscord,
  sendWebhookMessageDiscord,
  setChannelPermissionDiscord,
  setDiscordRuntime,
  setPresence,
  setThreadBindingIdleTimeoutBySessionKey,
  setThreadBindingMaxAgeBySessionKey,
  shouldEmitDiscordReactionNotification,
  timeoutMemberDiscord,
  unbindThreadBindingsBySessionKey,
  unpinMessageDiscord,
  unregisterGateway,
  uploadEmojiDiscord,
  uploadStickerDiscord,
  waitForDiscordGatewayPluginRegistration,
};
