import {
  n as resolveTelegramAccountConfig,
  t as mergeTelegramAccountConfig,
} from "../../account-config-BoAqzQvd.js";
import { t as inspectTelegramAccount } from "../../account-inspect-q-28bOgJ.js";
import {
  a as resolveDefaultTelegramAccountId,
  c as resolveTelegramPollActionGateState,
  i as resetMissingDefaultWarnFlag,
  n as listEnabledTelegramAccounts,
  o as resolveTelegramAccount,
  r as listTelegramAccountIds,
  s as resolveTelegramMediaRuntimeOptions,
  t as createTelegramActionGate,
} from "../../accounts-u_rpwiv9.js";
import {
  n as isNumericTelegramUserId,
  r as normalizeTelegramAllowFromEntry,
  t as isNumericTelegramSenderUserId,
} from "../../allow-from-CWtse-dx.js";
import {
  a as telegramOutbound,
  c as resolveTelegramGroupRequireMention,
  i as sendTelegramPayloadMessages,
  l as resolveTelegramGroupToolPolicy,
  n as collectTelegramStatusIssues,
  o as looksLikeTelegramTargetId,
  r as TELEGRAM_TEXT_CHUNK_LIMIT,
  s as normalizeTelegramMessagingTarget,
  t as telegramPlugin,
  u as resolveTelegramAutoThreadId,
} from "../../channel-CQ2Csdod.js";
import {
  d as resolveTelegramChatLookupFetch,
  l as fetchTelegramChatId,
  t as telegramSetupPlugin,
  u as lookupTelegramChatId,
} from "../../channel.setup-Bupwo4IT.js";
import {
  i as resolveTelegramCustomCommands,
  n as normalizeTelegramCommandDescription,
  r as normalizeTelegramCommandName,
  t as TELEGRAM_COMMAND_NAME_PATTERN,
} from "../../command-config-CVdcmiFR.js";
import {
  c as buildTelegramModelsProviderChannelData,
  d as buildModelsKeyboard,
  f as buildProviderKeyboard,
  g as resolveModelSelection,
  h as parseModelCallbackData,
  l as buildBrowseProvidersButton,
  m as getModelsPageSize,
  p as calculateTotalPages,
  t as buildCommandsPaginationKeyboard,
  u as buildModelSelectionCallbackData,
} from "../../command-ui-gBqv52UT.js";
import {
  n as listTelegramDirectoryPeersFromConfig,
  t as listTelegramDirectoryGroupsFromConfig,
} from "../../directory-config-bGoE6KWA.js";
import {
  a as isTelegramExecApprovalHandlerConfigured,
  c as resolveTelegramExecApprovalTarget,
  d as shouldInjectTelegramExecApprovalButtons,
  f as shouldSuppressLocalTelegramExecApprovalPrompt,
  i as isTelegramExecApprovalClientEnabled,
  l as shouldEnableTelegramExecApprovalButtons,
  n as isTelegramExecApprovalApprover,
  o as isTelegramExecApprovalTargetRecipient,
  r as isTelegramExecApprovalAuthorizedSender,
  s as resolveTelegramExecApprovalConfig,
  t as getTelegramExecApprovalApprovers,
  u as shouldHandleTelegramExecApprovalRequest,
} from "../../exec-approvals-Jy7fhfmT.js";
import {
  $ as parseTelegramReplyToMessageId,
  A as resolveTelegramReplyId,
  B as hasBotMention,
  D as resolveTelegramForumFlag,
  E as resolveTelegramDirectPeerId,
  F as buildSenderLabel,
  H as normalizeForwardedContext,
  I as buildSenderName,
  L as expandTextLinks,
  M as resolveTelegramThreadSpec,
  O as resolveTelegramForumThreadId,
  P as withResolvedTelegramForumFlag,
  Q as normalizeTelegramReplyToMessageId,
  R as extractTelegramLocation,
  S as extractTelegramForumFlag,
  U as resolveTelegramMediaPlaceholder,
  V as isBinaryContent,
  _ as buildTelegramParentPeer,
  at as resolveTelegramTargetChatType,
  b as buildTypingThreadParams,
  et as parseTelegramThreadId,
  g as buildTelegramGroupPeerId,
  h as buildTelegramGroupFrom,
  it as parseTelegramTarget,
  j as resolveTelegramStreamMode,
  k as resolveTelegramGroupAllowFromContext,
  m as buildGroupLabel,
  nt as normalizeTelegramChatId,
  ot as stripTelegramInternalPrefixes,
  rt as normalizeTelegramLookupTarget,
  tt as isNumericTelegramChatId,
  v as buildTelegramRoutingTarget,
  w as resetTelegramForumFlagCacheForTest,
  x as describeReplyTarget,
  y as buildTelegramThreadParams,
  z as getTelegramTextParts,
} from "../../format-xrIurvHN.js";
import {
  i as resolveTelegramInlineButtonsScopeFromCapabilities,
  n as resolveTelegramInlineButtonsConfigScope,
  r as resolveTelegramInlineButtonsScope,
  t as isTelegramInlineButtonsEnabled,
} from "../../inline-buttons-CG9H1O6u.js";
import {
  a as shouldSuppressTelegramExecApprovalForwardingFallback,
  i as buildTelegramExecApprovalPendingPayload,
  n as resetTelegramProbeFetcherCacheForTests,
  t as probeTelegram,
} from "../../probe-DwMlGujK.js";
import { t as resolveTelegramReactionLevel } from "../../reaction-level-CWOyYO9I.js";
import { t as collectTelegramSecurityAuditFindings } from "../../security-audit-Db-4GPeF.js";
import {
  a as getCachedSticker,
  i as getCacheStats,
  n as cacheSticker,
  o as searchStickers,
  r as getAllCachedStickers,
  t as describeStickerImage,
} from "../../sticker-cache-B9mKZWry.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-NVQ8tgVC.js";
import {
  n as readTelegramUpdateOffset,
  r as writeTelegramUpdateOffset,
  t as deleteTelegramUpdateOffset,
} from "../../update-offset-store-BadTVHDY.js";
export {
  TELEGRAM_COMMAND_NAME_PATTERN,
  TELEGRAM_TEXT_CHUNK_LIMIT,
  buildBrowseProvidersButton,
  buildCommandsPaginationKeyboard,
  buildGroupLabel,
  buildModelSelectionCallbackData,
  buildModelsKeyboard,
  buildProviderKeyboard,
  buildSenderLabel,
  buildSenderName,
  buildTelegramExecApprovalPendingPayload,
  buildTelegramGroupFrom,
  buildTelegramGroupPeerId,
  buildTelegramModelsProviderChannelData,
  buildTelegramParentPeer,
  buildTelegramRoutingTarget,
  buildTelegramThreadParams,
  buildTypingThreadParams,
  cacheSticker,
  calculateTotalPages,
  collectTelegramSecurityAuditFindings,
  collectTelegramStatusIssues,
  createTelegramActionGate,
  deleteTelegramUpdateOffset,
  describeReplyTarget,
  describeStickerImage,
  expandTextLinks,
  extractTelegramForumFlag,
  extractTelegramLocation,
  fetchTelegramChatId,
  getAllCachedStickers,
  getCacheStats,
  getCachedSticker,
  getModelsPageSize,
  getTelegramExecApprovalApprovers,
  getTelegramTextParts,
  hasBotMention,
  inspectTelegramAccount,
  isBinaryContent,
  isNumericTelegramChatId,
  isNumericTelegramSenderUserId,
  isNumericTelegramUserId,
  isTelegramExecApprovalApprover,
  isTelegramExecApprovalAuthorizedSender,
  isTelegramExecApprovalClientEnabled,
  isTelegramExecApprovalHandlerConfigured,
  isTelegramExecApprovalTargetRecipient,
  isTelegramInlineButtonsEnabled,
  listEnabledTelegramAccounts,
  listTelegramAccountIds,
  listTelegramDirectoryGroupsFromConfig,
  listTelegramDirectoryPeersFromConfig,
  looksLikeTelegramTargetId,
  lookupTelegramChatId,
  mergeTelegramAccountConfig,
  normalizeForwardedContext,
  normalizeTelegramAllowFromEntry,
  normalizeTelegramChatId,
  normalizeTelegramCommandDescription,
  normalizeTelegramCommandName,
  normalizeTelegramLookupTarget,
  normalizeTelegramMessagingTarget,
  normalizeTelegramReplyToMessageId,
  parseModelCallbackData,
  parseTelegramReplyToMessageId,
  parseTelegramTarget,
  parseTelegramThreadId,
  parseTelegramTopicConversation,
  probeTelegram,
  readTelegramUpdateOffset,
  resetMissingDefaultWarnFlag,
  resetTelegramForumFlagCacheForTest,
  resetTelegramProbeFetcherCacheForTests,
  resolveDefaultTelegramAccountId,
  resolveModelSelection,
  resolveTelegramAccount,
  resolveTelegramAccountConfig,
  resolveTelegramAutoThreadId,
  resolveTelegramChatLookupFetch,
  resolveTelegramCustomCommands,
  resolveTelegramDirectPeerId,
  resolveTelegramExecApprovalConfig,
  resolveTelegramExecApprovalTarget,
  resolveTelegramForumFlag,
  resolveTelegramForumThreadId,
  resolveTelegramGroupAllowFromContext,
  resolveTelegramGroupRequireMention,
  resolveTelegramGroupToolPolicy,
  resolveTelegramInlineButtonsConfigScope,
  resolveTelegramInlineButtonsScope,
  resolveTelegramInlineButtonsScopeFromCapabilities,
  resolveTelegramMediaPlaceholder,
  resolveTelegramMediaRuntimeOptions,
  resolveTelegramPollActionGateState,
  resolveTelegramReactionLevel,
  resolveTelegramReplyId,
  resolveTelegramStreamMode,
  resolveTelegramTargetChatType,
  resolveTelegramThreadSpec,
  searchStickers,
  sendTelegramPayloadMessages,
  shouldEnableTelegramExecApprovalButtons,
  shouldHandleTelegramExecApprovalRequest,
  shouldInjectTelegramExecApprovalButtons,
  shouldSuppressLocalTelegramExecApprovalPrompt,
  shouldSuppressTelegramExecApprovalForwardingFallback,
  stripTelegramInternalPrefixes,
  telegramOutbound,
  telegramPlugin,
  telegramSetupPlugin,
  withResolvedTelegramForumFlag,
  writeTelegramUpdateOffset,
};
