import {
  n as agentCommand,
  r as agentCommandFromIngress,
  t as __testing,
} from "../agent-command-bmrIHuJ_.js";
import {
  a as ToolPlanContractError,
  c as evaluateToolAvailability,
  i as formatToolExecutorRef,
  l as resolveModelCatalogScope,
  n as toToolProtocolDescriptors,
  o as defineToolDescriptor,
  r as buildToolPlan,
  s as defineToolDescriptors,
  t as toToolProtocolDescriptor,
  u as resolveProviderDiscoveryProviderIdsForCatalogScope,
} from "../agent-runtime-CG9i2LmY.js";
import {
  a as resolveAgentIdByWorkspacePath,
  c as resolveAgentModelPrimary,
  d as resolveFallbackAgentId,
  f as resolveRunModelFallbacksOverride,
  h as setAgentEffectiveModelPrimary,
  i as resolveAgentExplicitModelPrimary,
  l as resolveAgentSkillsFilter,
  m as resolveSessionAgentIds,
  n as resolveAgentEffectiveModelPrimary,
  o as resolveAgentIdsByWorkspacePath,
  p as resolveSessionAgentId,
  r as resolveAgentExecutionContract,
  s as resolveAgentModelFallbacksOverride,
  t as hasConfiguredModelFallbacks,
  u as resolveEffectiveModelFallbacks,
} from "../agent-scope-9AmhTwki.js";
import {
  a as resolveAgentDir,
  c as resolveDefaultAgentId,
  i as resolveAgentContextLimits,
  n as listAgentIds,
  o as resolveAgentWorkspaceDir,
  r as resolveAgentConfig,
  s as resolveDefaultAgentDir,
  t as listAgentEntries,
} from "../agent-scope-config-CXZGyKMl.js";
import {
  a as stripDowngradedToolCallText,
  d as stripModelSpecialTokens,
  s as stripMinimaxToolCallXml,
} from "../assistant-visible-text-DnuPT-bL.js";
import { i as resolveAuthProfileDisplayLabel } from "../auth-profiles-BrCJ7JK3.js";
import {
  _ as stringifyToolPayload,
  a as createActionGate,
  c as imageResultFromFile,
  d as payloadTextResult,
  f as readNumberParam,
  g as readStringParam,
  h as readStringOrNumberParam,
  i as asToolParamsRecord,
  l as jsonResult,
  m as readStringArrayParam,
  n as ToolAuthorizationError,
  o as failedTextResult,
  p as readReactionParams,
  r as ToolInputError,
  s as imageResult,
  t as OWNER_ONLY_TOOL_ERROR,
  u as parseAvailableTags,
  v as textResult,
  y as wrapOwnerOnlyToolExecution,
} from "../common-BPZLgNoA.js";
import {
  n as resolveCronStyleNow,
  t as appendCronStyleCurrentTimeLine,
} from "../current-time-DseN6ll4.js";
import {
  a as withNormalizedTimestamp,
  i as resolveUserTimezone,
  n as normalizeTimestamp,
  r as resolveUserTimeFormat,
  t as formatUserTime,
} from "../date-time-BBf0a32z.js";
import {
  n as DEFAULT_MODEL,
  r as DEFAULT_PROVIDER,
  t as DEFAULT_CONTEXT_TOKENS,
} from "../defaults-4m7JJmD2.js";
import {
  n as resolvePublicAgentAvatarSource,
  t as resolveAgentAvatar,
} from "../identity-avatar-CyG4ufH-.js";
import {
  a as resolveIdentityNamePrefix,
  i as resolveHumanDelayConfig,
  n as resolveAgentIdentity,
  o as resolveMessagePrefix,
  r as resolveEffectiveMessagesConfig,
  s as resolveResponsePrefix,
  t as resolveAckReaction,
} from "../identity-BfuOtf2o.js";
import {
  a as hasAvailableAuthForProvider,
  c as hasUsableCustomProviderApiKey,
  d as resolveUsableCustomProviderApiKey,
  f as shouldPreferExplicitConfigApiKeyAuth,
  i as getCustomProviderApiKey,
  l as resolveApiKeyForProvider,
  n as applyLocalNoAuthHeaderOverride,
  o as hasRuntimeAvailableProviderAuth,
  r as getApiKeyForModel,
  s as hasSyntheticLocalProviderAuthConfig,
  t as applyAuthHeaderOverride,
  u as resolveModelAuthMode,
} from "../model-auth-Do8Bfz1M.js";
import { t as resolveEnvApiKey } from "../model-auth-env-BTZHFDkv.js";
import {
  _ as resolveOAuthApiKeyMarker,
  a as OAUTH_API_KEY_MARKER_PREFIX,
  c as isAwsSdkAuthMarker,
  d as isOAuthApiKeyMarker,
  f as isSecretRefHeaderValueMarker,
  g as resolveNonEnvSecretRefHeaderValueMarker,
  h as resolveNonEnvSecretRefApiKeyMarker,
  i as NON_ENV_SECRETREF_MARKER,
  l as isKnownEnvApiKeyMarker,
  m as resolveEnvSecretRefHeaderValueMarker,
  n as GCP_VERTEX_CREDENTIALS_MARKER,
  o as OLLAMA_LOCAL_AUTH_MARKER,
  p as listKnownNonSecretApiKeyMarkers,
  r as MINIMAX_OAUTH_MARKER,
  s as SECRETREF_ENV_HEADER_MARKER_PREFIX,
  t as CUSTOM_LOCAL_AUTH_MARKER,
  u as isNonSecretApiKeyMarker,
} from "../model-auth-markers-CtsHE1k1.js";
import {
  n as resolveAwsSdkEnvVarName,
  t as requireApiKey,
} from "../model-auth-runtime-shared-DOaXxoUi.js";
import {
  a as modelSupportsVision,
  i as modelSupportsDocument,
  n as loadManifestModelCatalog,
  o as resetModelCatalogCache,
  r as loadModelCatalog,
  s as resetModelCatalogCacheForTest,
  t as __setModelCatalogImportForTest,
} from "../model-catalog-CJYpfYgw.js";
import { t as isCliProvider } from "../model-selection-cli-DuYeikT-.js";
import {
  a as resolveAllowedModelRef,
  c as resolvePersistedModelRef,
  d as resolveReasoningDefault,
  f as resolveSubagentConfiguredModelSelection,
  i as normalizeStoredOverrideModel,
  l as resolvePersistedOverrideModelRef,
  m as resolveThinkingDefault,
  n as canonicalizeCaseOnlyCatalogModelRef,
  o as resolveAllowlistModelKey,
  p as resolveSubagentSpawnModelSelection,
  r as getModelRefStatus,
  s as resolveDefaultModelForAgent,
  t as buildAllowedModelSet,
  u as resolvePersistedSelectedModelRef,
} from "../model-selection-CyVXHdEG.js";
import {
  C as modelSupportsInput,
  S as findModelInCatalog,
  _ as modelKey,
  c as normalizeModelSelection,
  d as resolveBareModelDefaultProvider,
  f as resolveConfiguredModelRef,
  g as legacyModelKey,
  h as resolveModelRefFromString,
  i as buildModelAliasIndex,
  m as resolveHooksGmailModel,
  n as buildConfiguredAllowlistKeys,
  o as inferUniqueProviderFromCatalog,
  r as buildConfiguredModelCatalog,
  s as inferUniqueProviderFromConfiguredModels,
  v as normalizeModelRef,
  x as findModelCatalogEntry,
  y as parseModelRef,
} from "../model-selection-shared-D9oQINZ2.js";
import { r as formatAuthDoctorHint, t as resolveApiKeyForProfile } from "../oauth-t1ja4_ir.js";
import {
  a as getSoonestCooldownExpiry,
  c as isProfileInCooldown,
  i as clearExpiredCooldowns,
  n as resolveAuthProfileEligibility,
  r as resolveAuthProfileOrder,
} from "../order-2B7dbn6U.js";
import { t as EmbeddedBlockChunker } from "../pi-embedded-block-chunker-CsOxWf1T.js";
import {
  a as extractThinkingFromTaggedStream,
  c as inferToolMetaFromArgs,
  d as splitThinkingTaggedText,
  f as stripThinkingTagsFromText,
  i as extractAssistantVisibleText,
  l as isAssistantMessage,
  n as extractAssistantText,
  o as extractThinkingFromTaggedText,
  r as extractAssistantThinking,
  s as formatReasoningMessage,
  t as THINKING_TAG_SCAN_RE,
  u as promoteThinkingTagsToBlocks,
} from "../pi-embedded-utils-DwjIPr7W.js";
import { n as listProfilesForProvider, t as dedupeProfileIds } from "../profile-list-B8KC6zHZ.js";
import {
  a as upsertAuthProfile,
  i as setAuthProfileOrder,
  o as upsertAuthProfileWithLock,
  t as markAuthProfileGood,
} from "../profiles-B4Bcz6fY.js";
import {
  n as resolveProviderAuthAliasMap,
  r as resolveProviderIdForAuth,
  t as resetProviderAuthAliasMapCacheForTest,
} from "../provider-auth-aliases-BsflYiD2.js";
import { g as resolveOpenClawAgentDir } from "../provider-auth-D0H8jtwm.js";
import {
  i as normalizeProviderIdForAuth,
  n as findNormalizedProviderValue,
  r as normalizeProviderId,
  t as findNormalizedProviderKey,
} from "../provider-id-CG9pXYPs.js";
import {
  n as suggestOAuthProfileIdForLegacyDefault,
  t as repairOAuthProfileIdMismatch,
} from "../repair-Dag1lBgW.js";
import {
  a as resolveSandboxPath,
  i as resolveSandboxInputPath,
  n as assertSandboxPath,
  o as resolveSandboxedMediaSource,
  r as resolveAllowedManagedMediaPath,
  t as assertMediaNotDataUrl,
} from "../sandbox-paths-BVIaOwJU.js";
import { u as resolveAgentIdFromSessionKey } from "../session-key-B4qUwRzq.js";
import {
  i as resolveSimpleCompletionSelectionForAgent,
  n as prepareSimpleCompletionModel,
  r as prepareSimpleCompletionModelForAgent,
  t as completeWithPreparedSimpleCompletionModel,
} from "../simple-completion-runtime-CeIwFtPw.js";
import { u as resolveAuthStorePathForDisplay } from "../source-check-DUt28S7k.js";
import {
  M as CLAUDE_CLI_PROFILE_ID,
  N as CODEX_CLI_PROFILE_ID,
  a as findPersistedAuthProfileCredential,
  c as loadAuthProfileStoreForSecretsRuntime,
  d as resolvePersistedAuthProfileOwnerAgentDir,
  f as saveAuthProfileStore,
  i as ensureAuthProfileStoreWithoutExternalProfiles,
  l as loadAuthProfileStoreWithoutExternalProfiles,
  n as ensureAuthProfileStore,
  o as loadAuthProfileStore,
  s as loadAuthProfileStoreForRuntime,
  t as clearRuntimeAuthProfileStoreSnapshots,
  u as replaceRuntimeAuthProfileStoreSnapshots,
} from "../store-9hg03xJO.js";
import {
  A as textToSpeechStream,
  C as setTtsEnabled,
  D as streamSpeech,
  E as setTtsProvider,
  O as synthesizeSpeech,
  S as setTtsAutoMode,
  T as setTtsPersona,
  _ as resolveTtsConfig,
  a as getTtsMaxLength,
  b as setLastTtsAttempt,
  c as isSummarizationEnabled,
  d as listSpeechVoices,
  f as listTtsPersonas,
  g as resolveTtsAutoMode,
  h as resolveExplicitTtsOverrides,
  i as getResolvedSpeechProviderConfig,
  j as textToSpeechTelephony,
  k as textToSpeech,
  l as isTtsEnabled,
  n as buildTtsSystemPromptHint,
  o as getTtsPersona,
  p as maybeApplyTtsToPayload,
  r as getLastTtsAttempt,
  s as getTtsProvider,
  t as _test,
  u as isTtsProviderConfigured,
  v as resolveTtsPrefsPath,
  w as setTtsMaxLength,
  x as setSummarizationEnabled,
  y as resolveTtsProviderOrder,
} from "../tts-runtime-CfX4V8Mc.js";
import {
  i as stringEnum,
  n as channelTargetsSchema,
  r as optionalStringEnum,
  t as channelTargetSchema,
} from "../typebox-DifzaH7c.js";
import {
  a as markAuthProfileUsed,
  i as markAuthProfileFailure,
  n as clearAuthProfileCooldown,
  o as resolveProfileUnusableUntilForDisplay,
  r as markAuthProfileCooldown,
  s as resolveProfilesUnavailableReason,
  t as calculateAuthProfileCooldownMs,
} from "../usage-BOP5ZbfL.js";
import {
  a as truncateText,
  i as normalizeWhitespace,
  n as htmlToMarkdown,
  r as markdownToText,
  t as extractBasicHtmlContent,
} from "../web-fetch-utils-Bpv806jB.js";
import {
  i as withTrustedWebToolsEndpoint,
  n as withSelfHostedWebToolsEndpoint,
  r as withStrictWebToolsEndpoint,
  t as fetchWithWebToolsNetworkGuard,
} from "../web-guarded-fetch-BPkziv1R.js";
import {
  a as readResponseText,
  c as withTimeout,
  i as readCache,
  l as writeCache,
  n as DEFAULT_TIMEOUT_SECONDS,
  o as resolveCacheTtlMs,
  r as normalizeCacheKey,
  s as resolveTimeoutSeconds,
  t as DEFAULT_CACHE_TTL_MINUTES,
} from "../web-shared-MM6C0FoP.js";
export {
  CLAUDE_CLI_PROFILE_ID,
  CODEX_CLI_PROFILE_ID,
  CUSTOM_LOCAL_AUTH_MARKER,
  DEFAULT_CACHE_TTL_MINUTES,
  DEFAULT_CONTEXT_TOKENS,
  DEFAULT_MODEL,
  DEFAULT_PROVIDER,
  DEFAULT_TIMEOUT_SECONDS,
  EmbeddedBlockChunker,
  GCP_VERTEX_CREDENTIALS_MARKER,
  MINIMAX_OAUTH_MARKER,
  NON_ENV_SECRETREF_MARKER,
  OAUTH_API_KEY_MARKER_PREFIX,
  OLLAMA_LOCAL_AUTH_MARKER,
  OWNER_ONLY_TOOL_ERROR,
  SECRETREF_ENV_HEADER_MARKER_PREFIX,
  THINKING_TAG_SCAN_RE,
  ToolAuthorizationError,
  ToolInputError,
  ToolPlanContractError,
  __setModelCatalogImportForTest,
  __testing,
  _test,
  agentCommand,
  agentCommandFromIngress,
  appendCronStyleCurrentTimeLine,
  applyAuthHeaderOverride,
  applyLocalNoAuthHeaderOverride,
  asToolParamsRecord,
  assertMediaNotDataUrl,
  assertSandboxPath,
  buildAllowedModelSet,
  buildConfiguredAllowlistKeys,
  buildConfiguredModelCatalog,
  buildModelAliasIndex,
  buildToolPlan,
  buildTtsSystemPromptHint,
  calculateAuthProfileCooldownMs,
  canonicalizeCaseOnlyCatalogModelRef,
  channelTargetSchema,
  channelTargetsSchema,
  clearAuthProfileCooldown,
  clearExpiredCooldowns,
  clearRuntimeAuthProfileStoreSnapshots,
  completeWithPreparedSimpleCompletionModel,
  createActionGate,
  dedupeProfileIds,
  defineToolDescriptor,
  defineToolDescriptors,
  ensureAuthProfileStore,
  ensureAuthProfileStoreWithoutExternalProfiles,
  evaluateToolAvailability,
  extractAssistantText,
  extractAssistantThinking,
  extractAssistantVisibleText,
  extractBasicHtmlContent,
  extractThinkingFromTaggedStream,
  extractThinkingFromTaggedText,
  failedTextResult,
  fetchWithWebToolsNetworkGuard,
  findModelCatalogEntry,
  findModelInCatalog,
  findNormalizedProviderKey,
  findNormalizedProviderValue,
  findPersistedAuthProfileCredential,
  formatAuthDoctorHint,
  formatReasoningMessage,
  formatToolExecutorRef,
  formatUserTime,
  getApiKeyForModel,
  getCustomProviderApiKey,
  getLastTtsAttempt,
  getModelRefStatus,
  getResolvedSpeechProviderConfig,
  getSoonestCooldownExpiry,
  getTtsMaxLength,
  getTtsPersona,
  getTtsProvider,
  hasAvailableAuthForProvider,
  hasConfiguredModelFallbacks,
  hasRuntimeAvailableProviderAuth,
  hasSyntheticLocalProviderAuthConfig,
  hasUsableCustomProviderApiKey,
  htmlToMarkdown,
  imageResult,
  imageResultFromFile,
  inferToolMetaFromArgs,
  inferUniqueProviderFromCatalog,
  inferUniqueProviderFromConfiguredModels,
  isAssistantMessage,
  isAwsSdkAuthMarker,
  isCliProvider,
  isKnownEnvApiKeyMarker,
  isNonSecretApiKeyMarker,
  isOAuthApiKeyMarker,
  isProfileInCooldown,
  isSecretRefHeaderValueMarker,
  isSummarizationEnabled,
  isTtsEnabled,
  isTtsProviderConfigured,
  jsonResult,
  legacyModelKey,
  listAgentEntries,
  listAgentIds,
  listKnownNonSecretApiKeyMarkers,
  listProfilesForProvider,
  listSpeechVoices,
  listTtsPersonas,
  loadAuthProfileStore,
  loadAuthProfileStoreForRuntime,
  loadAuthProfileStoreForSecretsRuntime,
  loadAuthProfileStoreWithoutExternalProfiles,
  loadManifestModelCatalog,
  loadModelCatalog,
  markAuthProfileCooldown,
  markAuthProfileFailure,
  markAuthProfileGood,
  markAuthProfileUsed,
  markdownToText,
  maybeApplyTtsToPayload,
  modelKey,
  modelSupportsDocument,
  modelSupportsInput,
  modelSupportsVision,
  normalizeCacheKey,
  normalizeModelRef,
  normalizeModelSelection,
  normalizeProviderId,
  normalizeProviderIdForAuth,
  normalizeStoredOverrideModel,
  normalizeTimestamp,
  normalizeWhitespace,
  optionalStringEnum,
  parseAvailableTags,
  parseModelRef,
  payloadTextResult,
  prepareSimpleCompletionModel,
  prepareSimpleCompletionModelForAgent,
  promoteThinkingTagsToBlocks,
  readCache,
  readNumberParam,
  readReactionParams,
  readResponseText,
  readStringArrayParam,
  readStringOrNumberParam,
  readStringParam,
  repairOAuthProfileIdMismatch,
  replaceRuntimeAuthProfileStoreSnapshots,
  requireApiKey,
  resetModelCatalogCache,
  resetModelCatalogCacheForTest,
  resetProviderAuthAliasMapCacheForTest,
  resolveAckReaction,
  resolveAgentAvatar,
  resolveAgentConfig,
  resolveAgentContextLimits,
  resolveAgentDir,
  resolveAgentEffectiveModelPrimary,
  resolveAgentExecutionContract,
  resolveAgentExplicitModelPrimary,
  resolveAgentIdByWorkspacePath,
  resolveAgentIdFromSessionKey,
  resolveAgentIdentity,
  resolveAgentIdsByWorkspacePath,
  resolveAgentModelFallbacksOverride,
  resolveAgentModelPrimary,
  resolveAgentSkillsFilter,
  resolveAgentWorkspaceDir,
  resolveAllowedManagedMediaPath,
  resolveAllowedModelRef,
  resolveAllowlistModelKey,
  resolveApiKeyForProfile,
  resolveApiKeyForProvider,
  resolveAuthProfileDisplayLabel,
  resolveAuthProfileEligibility,
  resolveAuthProfileOrder,
  resolveAuthStorePathForDisplay,
  resolveAwsSdkEnvVarName,
  resolveBareModelDefaultProvider,
  resolveCacheTtlMs,
  resolveConfiguredModelRef,
  resolveCronStyleNow,
  resolveDefaultAgentDir,
  resolveDefaultAgentId,
  resolveDefaultModelForAgent,
  resolveEffectiveMessagesConfig,
  resolveEffectiveModelFallbacks,
  resolveEnvApiKey,
  resolveEnvSecretRefHeaderValueMarker,
  resolveExplicitTtsOverrides,
  resolveFallbackAgentId,
  resolveHooksGmailModel,
  resolveHumanDelayConfig,
  resolveIdentityNamePrefix,
  resolveMessagePrefix,
  resolveModelAuthMode,
  resolveModelCatalogScope,
  resolveModelRefFromString,
  resolveNonEnvSecretRefApiKeyMarker,
  resolveNonEnvSecretRefHeaderValueMarker,
  resolveOAuthApiKeyMarker,
  resolveOpenClawAgentDir,
  resolvePersistedAuthProfileOwnerAgentDir,
  resolvePersistedModelRef,
  resolvePersistedOverrideModelRef,
  resolvePersistedSelectedModelRef,
  resolveProfileUnusableUntilForDisplay,
  resolveProfilesUnavailableReason,
  resolveProviderAuthAliasMap,
  resolveProviderDiscoveryProviderIdsForCatalogScope,
  resolveProviderIdForAuth,
  resolvePublicAgentAvatarSource,
  resolveReasoningDefault,
  resolveResponsePrefix,
  resolveRunModelFallbacksOverride,
  resolveSandboxInputPath,
  resolveSandboxPath,
  resolveSandboxedMediaSource,
  resolveSessionAgentId,
  resolveSessionAgentIds,
  resolveSimpleCompletionSelectionForAgent,
  resolveSubagentConfiguredModelSelection,
  resolveSubagentSpawnModelSelection,
  resolveThinkingDefault,
  resolveTimeoutSeconds,
  resolveTtsAutoMode,
  resolveTtsConfig,
  resolveTtsPrefsPath,
  resolveTtsProviderOrder,
  resolveUsableCustomProviderApiKey,
  resolveUserTimeFormat,
  resolveUserTimezone,
  saveAuthProfileStore,
  setAgentEffectiveModelPrimary,
  setAuthProfileOrder,
  setLastTtsAttempt,
  setSummarizationEnabled,
  setTtsAutoMode,
  setTtsEnabled,
  setTtsMaxLength,
  setTtsPersona,
  setTtsProvider,
  shouldPreferExplicitConfigApiKeyAuth,
  splitThinkingTaggedText,
  streamSpeech,
  stringEnum,
  stringifyToolPayload,
  stripDowngradedToolCallText,
  stripMinimaxToolCallXml,
  stripModelSpecialTokens,
  stripThinkingTagsFromText,
  suggestOAuthProfileIdForLegacyDefault,
  synthesizeSpeech,
  textResult,
  textToSpeech,
  textToSpeechStream,
  textToSpeechTelephony,
  toToolProtocolDescriptor,
  toToolProtocolDescriptors,
  truncateText,
  upsertAuthProfile,
  upsertAuthProfileWithLock,
  withNormalizedTimestamp,
  withSelfHostedWebToolsEndpoint,
  withStrictWebToolsEndpoint,
  withTimeout,
  withTrustedWebToolsEndpoint,
  wrapOwnerOnlyToolExecution,
  writeCache,
};
