import { t as formatApprovalDisplayPath } from "../approval-display-paths-z_-7Vskn.js";
import {
  a as isExecApprovalChannelRuntimeTerminalStartError,
  i as createExecApprovalChannelRuntime,
  n as deliverApprovalRequestViaChannelNativePlan,
  o as resolveChannelNativeApprovalDeliveryPlan,
  r as ExecApprovalChannelRuntimeTerminalStartError,
  t as createChannelNativeApprovalRuntime,
} from "../approval-native-runtime-Jhr06_E7.js";
import { t as createAsyncLock } from "../async-lock-Cp5JQa-X.js";
import { n as sleepWithAbort, t as computeBackoff } from "../backoff-CW9s2Y7t.js";
import {
  n as recordChannelActivity,
  r as resetChannelActivityForTest,
  t as getChannelActivity,
} from "../channel-activity-C42T8R8o.js";
import { n as resolveGlobalDedupeCache, t as createDedupeCache } from "../dedupe-DxEPwz5a.js";
import { t as drainPendingDeliveries } from "../delivery-queue-runtime-BHw0P29a.js";
import {
  a as isDiagnosticsEnabled,
  n as emitDiagnosticEvent,
  o as onDiagnosticEvent,
  t as areDiagnosticsEnabledForProcess,
} from "../diagnostic-events-9isI4hMq.js";
import {
  n as matchesDiagnosticFlag,
  r as resolveDiagnosticFlags,
  t as isDiagnosticFlagEnabled,
} from "../diagnostic-flags-CQ-HLl8y.js";
import {
  a as normalizeZaiEnv,
  i as normalizeEnv,
  n as isVitestRuntimeEnv,
  r as logAcceptedEnvOption,
  t as isTruthyEnvValue,
} from "../env-GyTZ5xFK.js";
import {
  a as formatErrorMessage,
  c as isErrno,
  i as extractErrorCode,
  l as readErrorName,
  n as collectErrorGraphCandidates,
  o as formatUncaughtError,
  r as detectErrorKind,
  s as hasErrnoCode,
  t as SocketDropException,
} from "../errors-DZMrVkYL.js";
import {
  n as sanitizeExecApprovalDisplayText,
  r as sanitizeExecApprovalWarningText,
  t as resolveExecApprovalCommandDisplay,
} from "../exec-approval-command-display-C0QT0abP.js";
import {
  a as buildExecApprovalInteractiveReply,
  c as formatExecApprovalExpiresIn,
  d as parseExecApprovalCommandText,
  i as buildExecApprovalCommandText,
  l as getExecApprovalApproverDmNoticeText,
  n as buildApprovalInteractiveReplyFromActionDescriptors,
  o as buildExecApprovalPendingReplyPayload,
  r as buildExecApprovalActionDescriptors,
  s as buildExecApprovalUnavailableReplyPayload,
  t as buildApprovalInteractiveReply,
  u as getExecApprovalReplyMetadata,
} from "../exec-approval-reply-BPlmHS3G.js";
import {
  i as resolveExecApprovalSessionTarget,
  n as resolveApprovalRequestSessionConversation,
  r as resolveApprovalRequestSessionTarget,
  t as resolveApprovalRequestOriginTarget,
} from "../exec-approval-session-target-D1FPh_og.js";
import {
  _ as windowsEscapeArg,
  a as resolveAllowAlwaysPatternEntries,
  c as analyzeArgvCommand,
  d as buildSafeBinsShellCommand,
  f as buildSafeShellCommand,
  g as splitCommandChainWithOperators,
  h as splitCommandChain,
  i as normalizeSafeBins,
  l as analyzeShellCommand,
  m as resolvePlannedSegmentArgv,
  n as evaluateShellAllowlist,
  o as resolveAllowAlwaysPatterns,
  p as isWindowsPlatform,
  r as isSafeBinUsage,
  s as resolveSafeBins,
  t as evaluateExecAllowlist,
  u as buildEnforcedShellCommand,
} from "../exec-approvals-allowlist-wYeDXb0Q.js";
import {
  A as resolveExecApprovalsPath,
  C as requestExecApprovalViaSocket,
  D as resolveExecApprovalRequestAllowedDecisions,
  E as resolveExecApprovalAllowedDecisions,
  M as restoreExecApprovalsSnapshot,
  N as saveExecApprovals,
  O as resolveExecApprovals,
  S as recordAllowlistUse,
  T as requiresExecApproval,
  _ as normalizeExecSecurity,
  a as addAllowlistEntry,
  b as readExecApprovalsSnapshot,
  c as hasDurableExecApproval,
  d as maxAsk,
  f as mergeExecApprovalsSocketDefaults,
  g as normalizeExecHost,
  h as normalizeExecAsk,
  i as EXEC_TARGET_VALUES,
  j as resolveExecApprovalsSocketPath,
  k as resolveExecApprovalsFromFile,
  l as isExecApprovalDecisionAllowed,
  m as normalizeExecApprovals,
  n as DEFAULT_EXEC_APPROVAL_DECISIONS,
  o as addDurableCommandApproval,
  p as minSecurity,
  r as DEFAULT_EXEC_APPROVAL_TIMEOUT_MS,
  s as ensureExecApprovals,
  t as DEFAULT_EXEC_APPROVAL_ASK_FALLBACK,
  u as loadExecApprovals,
  v as normalizeExecTarget,
  w as requireValidExecTarget,
  x as recordAllowlistMatchesUse,
  y as persistAllowAlwaysPatterns,
} from "../exec-approvals-VkyGhwX9.js";
import {
  _ as resolvePolicyTargetCandidatePath,
  c as matchAllowlist,
  d as resolveApprovalAuditCandidatePath,
  f as resolveCommandResolution,
  g as resolvePolicyAllowlistCandidatePath,
  h as resolveExecutionTargetResolution,
  l as parseExecArgvToken,
  m as resolveExecutionTargetCandidatePath,
  p as resolveCommandResolutionFromArgv,
  u as resolveAllowlistCandidatePath,
  v as resolvePolicyTargetResolution,
} from "../exec-safe-bin-trust-D3CIZbMH.js";
import { n as wrapFetchWithAbortSignal, t as resolveFetch } from "../fetch-Cwtbr1ux.js";
import {
  a as withTrustedEnvProxyGuardedFetchMode,
  i as withStrictGuardedFetchMode,
  n as fetchWithSsrFGuard,
  o as withTrustedExplicitProxyGuardedFetchMode,
  r as retainSafeHeadersForCrossOriginRedirectHeaders,
  t as GUARDED_FETCH_MODE,
} from "../fetch-guard-jcadyt5o.js";
import {
  n as buildTimeoutAbortSignal,
  r as fetchWithTimeout,
  t as bindAbortRelay,
} from "../fetch-timeout-Df3EC-Xg.js";
import {
  a as withFileLock,
  i as resetFileLockStateForTest,
  n as acquireFileLock,
  r as drainFileLockStateForTest,
  t as FILE_LOCK_TIMEOUT_ERROR_CODE,
} from "../file-lock-C5nUdr1w.js";
import {
  i as formatDurationSeconds,
  n as formatDurationHuman,
  r as formatDurationPrecise,
  t as formatDurationCompact,
} from "../format-duration-DV-29w1K.js";
import "../file-lock-Deo0YuAs.js";
import {
  A as findExistingAncestor,
  C as safeFileURLToPath,
  D as sanitizeUntrustedFileName,
  E as pathExistsSync,
  M as resolveAbsolutePathForWrite,
  O as assertAbsolutePathInput,
  S as isWindowsNetworkPath,
  T as pathExists,
  _ as readLocalFileFromRoots,
  a as walkDirectory,
  b as basenameFromMediaSource,
  i as writeFileWithinRoot,
  j as resolveAbsolutePathForRead,
  k as canonicalPathFromExistingAncestor,
  n as readFileWithinRoot,
  o as walkDirectorySync,
  r as writeExternalFileWithinRoot,
  s as readSecureFile,
  t as ensureAbsoluteDirectory,
  u as withTimeout,
  v as resolveLocalPathFromRootsSync,
  w as trySafeFileURLToPath,
  x as hasEncodedFileUrlSeparator,
  y as assertNoWindowsNetworkPath,
} from "../fs-safe-CgBWiL92.js";
import {
  a as resolveIndicatorType,
  i as resetHeartbeatEventsForTest,
  n as getLastHeartbeatEvent,
  r as onHeartbeatEvent,
  t as emitHeartbeatEvent,
} from "../heartbeat-events-Dux0y1fS.js";
import {
  n as resolveHeartbeatIntervalMs,
  r as resolveHeartbeatSummaryForAgent,
  t as isHeartbeatEnabledForAgent,
} from "../heartbeat-summary-9lfm3C_j.js";
import { t as resolveHeartbeatVisibility } from "../heartbeat-visibility-zxoFzbvk.js";
import {
  a as resolveOsHomeRelativePath,
  c as resolveUserPath,
  i as resolveOsHomeDir,
  n as resolveEffectiveHomeDir,
  o as resolveRequiredHomeDir,
  r as resolveHomeRelativePath,
  s as resolveRequiredOsHomeDir,
  t as expandHomePrefix,
} from "../home-dir-iZwpu-40.js";
import { t as normalizeHostname } from "../hostname-DOneeF6p.js";
import {
  a as isRequestBodyLimitError,
  c as requestBodyErrorToText,
  i as installRequestBodyLimitGuard,
  n as DEFAULT_WEBHOOK_MAX_BODY_BYTES,
  o as readJsonBodyWithLimit,
  r as RequestBodyLimitError,
  s as readRequestBodyWithLimit,
  t as DEFAULT_WEBHOOK_BODY_TIMEOUT_MS,
} from "../http-body-D8UGuStR.js";
import {
  n as resolveAgentOutboundIdentity,
  t as normalizeOutboundIdentity,
} from "../identity-j0n6E1vW.js";
import {
  a as readJsonSync,
  c as readRootStructuredFileSync,
  d as writeJson,
  f as writeJsonSync,
  i as readJsonIfExists,
  l as tryReadJson,
  n as JsonFileReadError,
  o as readRootJsonObjectSync,
  r as readJson,
  s as readRootJsonSync,
  t as writeTextAtomic,
  u as tryReadJsonSync,
} from "../json-files-DifBk3kt.js";
import { t as pruneMapToMaxSize } from "../map-size-BTgIZSQN.js";
import "../local-file-access-KUGx5XDy.js";
import {
  i as parseStrictPositiveInteger,
  n as parseStrictInteger,
  r as parseStrictNonNegativeInteger,
  t as parseFiniteNumber,
} from "../parse-finite-number-Bfn_46hj.js";
import { i as isPathInside, p as FsSafeError } from "../path-1liOXr_N.js";
import {
  a as PLUGIN_APPROVAL_TITLE_MAX_LENGTH,
  c as buildPluginApprovalRequestMessage,
  i as PLUGIN_APPROVAL_DESCRIPTION_MAX_LENGTH,
  l as buildPluginApprovalResolvedMessage,
  n as DEFAULT_PLUGIN_APPROVAL_TIMEOUT_MS,
  o as approvalDecisionLabel,
  r as MAX_PLUGIN_APPROVAL_TIMEOUT_MS,
  s as buildPluginApprovalExpiredMessage,
  t as DEFAULT_PLUGIN_APPROVAL_DECISIONS,
  u as resolvePluginApprovalRequestAllowedDecisions,
} from "../plugin-approvals-DS5L8BzN.js";
import {
  a as matchesNoProxy,
  c as shouldUseEnvHttpProxyForUrl,
  i as hasProxyEnvConfigured,
  n as hasEnvHttpProxyAgentConfigured,
  o as resolveEnvHttpProxyAgentOptions,
  r as hasEnvHttpProxyConfigured,
  s as resolveEnvHttpProxyUrl,
  t as PROXY_ENV_KEYS,
} from "../proxy-env-C3VNcjQ7.js";
import {
  i as resolveProxyFetchFromEnv,
  n as getProxyUrlFromFetch,
  r as makeProxyFetch,
  t as PROXY_FETCH_PROXY_URL,
} from "../proxy-fetch-Dt1coO5G.js";
import {
  a as resolveRegularFileAppendFlags,
  i as readRegularFileSync,
  n as appendRegularFileSync,
  r as readRegularFile,
  s as statRegularFileSync,
  t as appendRegularFile,
} from "../regular-file-CoVHB-2u.js";
import { n as retryAsync, t as resolveRetryConfig } from "../retry-eUGQeeNu.js";
import {
  n as createChannelApiRetryRunner,
  r as createRateLimitRetryRunner,
  t as CHANNEL_API_RETRY_DEFAULTS,
} from "../retry-policy-CBO_PUda.js";
import { t as runTasksWithConcurrency } from "../run-with-concurrency-BurDsdaa.js";
import { t as fetchWithRuntimeDispatcher } from "../runtime-fetch-DhU7fIOQ.js";
import { n as createRuntimeOutboundDelegates } from "../runtime-forwarders-zg2wxLcy.js";
import {
  n as stripInternalRuntimeScaffolding,
  t as sanitizeForPlainText,
} from "../sanitize-text-CR0zkUDk.js";
import {
  i as normalizeScpRemotePath,
  n as isSafeScpRemotePath,
  r as normalizeScpRemoteHost,
  t as isSafeScpRemoteHost,
} from "../scp-host-4o-2UHZG.js";
import {
  a as tryReadSecretFileSync,
  i as readSecretFileSync,
  n as PRIVATE_SECRET_DIR_MODE,
  o as writeSecretFileAtomic,
  r as PRIVATE_SECRET_FILE_MODE,
  t as DEFAULT_SECRET_FILE_MAX_BYTES,
} from "../secret-file-CvOsk3nE.js";
import { t as loadSecretFileSync } from "../secret-file-DPekPhW_.js";
import {
  a as generateSecureUuid,
  i as generateSecureToken,
  n as generateSecureHex,
  r as generateSecureInt,
  t as generateSecureFraction,
} from "../secure-random-Ck_jpq4r.js";
import {
  a as resolveOpenedFileRealPathForHandle,
  i as readLocalFileSafely,
  o as root,
  r as openLocalFileSafely,
} from "../secure-temp-dir-CCj3cY2B.js";
import {
  n as resolveOutboundSendDep,
  t as resolveLegacyOutboundSendDepKeys,
} from "../send-deps-CtmJEFTh.js";
import {
  _ as ssrfPolicyFromHttpBaseUrlAllowedHostname,
  a as createPinnedDispatcher,
  c as isBlockedHostnameOrIp,
  d as isPrivateNetworkAllowedByPolicy,
  f as isSameSsrFPolicy,
  g as resolvePinnedHostnameWithPolicy,
  h as resolvePinnedHostname,
  i as closeDispatcher,
  l as isHostnameAllowedByPattern,
  m as normalizeHostnameAllowlist,
  n as assertHostnameAllowedWithPolicy,
  o as createPinnedLookup,
  p as matchesHostnameAllowlist,
  r as assertPublicHostname,
  s as isBlockedHostname,
  t as SsrFBlockedError,
  u as isPrivateIpAddress,
  v as ssrfPolicyFromHttpBaseUrlFakeIpHostnameAllowlist,
} from "../ssrf-DO8eIXaD.js";
import {
  a as isHttpsUrlAllowedByHostnameSuffixAllowlist,
  c as migrateLegacyFlatAllowPrivateNetworkAlias,
  d as ssrfPolicyFromDangerouslyAllowPrivateNetwork,
  f as ssrfPolicyFromPrivateNetworkOptIn,
  i as hasLegacyFlatAllowPrivateNetworkAlias,
  l as normalizeHostnameSuffixAllowlist,
  n as buildHostnameAllowlistPolicyFromSuffixAllowlist,
  o as isPrivateNetworkOptInEnabled,
  r as createLegacyPrivateNetworkDoctorContract,
  s as mergeSsrFPolicies,
  t as assertHttpUrlTargetsPrivateNetwork,
  u as ssrfPolicyFromAllowPrivateNetwork,
} from "../ssrf-policy-CLYqev3x.js";
import {
  a as enqueueSystemEvent,
  c as peekSystemEventEntries,
  d as resolveSystemEventDeliveryContext,
  i as drainSystemEvents,
  l as peekSystemEvents,
  n as consumeSystemEventEntries,
  o as hasSystemEvents,
  r as drainSystemEventEntries,
  s as isSystemEventContextChanged,
  t as consumeSelectedSystemEventEntries,
  u as resetSystemEventsForTest,
} from "../system-events-CttxBeh2.js";
import {
  n as hasSystemMark,
  r as prefixSystemMessage,
  t as SYSTEM_MARK,
} from "../system-message-OiD4avN2.js";
import {
  n as resolvePreferredOpenClawTmpDir,
  t as POSIX_OPENCLAW_TMP_DIR,
} from "../tmp-openclaw-dir-B4r8YQhH.js";
import { t as waitForTransportReady } from "../transport-ready-DS1UbeMl.js";
import {
  a as ensureGlobalUndiciStreamTimeouts,
  i as ensureGlobalUndiciEnvProxyDispatcher,
  n as _globalUndiciStreamTimeoutMs,
  o as forceResetGlobalDispatcher,
  r as ensureGlobalUndiciDispatcherStreamTimeouts,
  s as resetGlobalUndiciStreamTimeoutsForTests,
  t as DEFAULT_UNDICI_STREAM_TIMEOUT_MS,
} from "../undici-global-dispatcher-B1L_za-h.js";
import {
  a as resetWSLStateForTests,
  i as isWSLSync,
  n as isWSL2Sync,
  r as isWSLEnv,
  t as isWSL,
} from "../wsl-DVnK6WpM.js";
export {
  CHANNEL_API_RETRY_DEFAULTS,
  DEFAULT_EXEC_APPROVAL_ASK_FALLBACK,
  DEFAULT_EXEC_APPROVAL_DECISIONS,
  DEFAULT_EXEC_APPROVAL_TIMEOUT_MS,
  DEFAULT_PLUGIN_APPROVAL_DECISIONS,
  DEFAULT_PLUGIN_APPROVAL_TIMEOUT_MS,
  DEFAULT_SECRET_FILE_MAX_BYTES,
  DEFAULT_UNDICI_STREAM_TIMEOUT_MS,
  DEFAULT_WEBHOOK_BODY_TIMEOUT_MS,
  DEFAULT_WEBHOOK_MAX_BODY_BYTES,
  EXEC_TARGET_VALUES,
  ExecApprovalChannelRuntimeTerminalStartError,
  FILE_LOCK_TIMEOUT_ERROR_CODE,
  FsSafeError,
  GUARDED_FETCH_MODE,
  JsonFileReadError,
  MAX_PLUGIN_APPROVAL_TIMEOUT_MS,
  PLUGIN_APPROVAL_DESCRIPTION_MAX_LENGTH,
  PLUGIN_APPROVAL_TITLE_MAX_LENGTH,
  POSIX_OPENCLAW_TMP_DIR,
  PRIVATE_SECRET_DIR_MODE,
  PRIVATE_SECRET_FILE_MODE,
  PROXY_ENV_KEYS,
  PROXY_FETCH_PROXY_URL,
  RequestBodyLimitError,
  SYSTEM_MARK,
  SocketDropException,
  SsrFBlockedError,
  _globalUndiciStreamTimeoutMs,
  acquireFileLock,
  addAllowlistEntry,
  addDurableCommandApproval,
  analyzeArgvCommand,
  analyzeShellCommand,
  appendRegularFile,
  appendRegularFileSync,
  approvalDecisionLabel,
  areDiagnosticsEnabledForProcess,
  assertAbsolutePathInput,
  assertHostnameAllowedWithPolicy,
  assertHttpUrlTargetsPrivateNetwork,
  assertNoWindowsNetworkPath,
  assertPublicHostname,
  basenameFromMediaSource,
  bindAbortRelay,
  buildApprovalInteractiveReply,
  buildApprovalInteractiveReplyFromActionDescriptors,
  buildEnforcedShellCommand,
  buildExecApprovalActionDescriptors,
  buildExecApprovalCommandText,
  buildExecApprovalInteractiveReply,
  buildExecApprovalPendingReplyPayload,
  buildExecApprovalUnavailableReplyPayload,
  buildHostnameAllowlistPolicyFromSuffixAllowlist,
  buildPluginApprovalExpiredMessage,
  buildPluginApprovalRequestMessage,
  buildPluginApprovalResolvedMessage,
  buildSafeBinsShellCommand,
  buildSafeShellCommand,
  buildTimeoutAbortSignal,
  canonicalPathFromExistingAncestor,
  closeDispatcher,
  collectErrorGraphCandidates,
  computeBackoff,
  consumeSelectedSystemEventEntries,
  consumeSystemEventEntries,
  createAsyncLock,
  createChannelApiRetryRunner,
  createChannelNativeApprovalRuntime,
  createDedupeCache,
  createExecApprovalChannelRuntime,
  createLegacyPrivateNetworkDoctorContract,
  createPinnedDispatcher,
  createPinnedLookup,
  createRateLimitRetryRunner,
  createRuntimeOutboundDelegates,
  deliverApprovalRequestViaChannelNativePlan,
  detectErrorKind,
  drainFileLockStateForTest,
  drainPendingDeliveries,
  drainSystemEventEntries,
  drainSystemEvents,
  emitDiagnosticEvent,
  emitHeartbeatEvent,
  enqueueSystemEvent,
  ensureAbsoluteDirectory,
  ensureExecApprovals,
  ensureGlobalUndiciDispatcherStreamTimeouts,
  ensureGlobalUndiciEnvProxyDispatcher,
  ensureGlobalUndiciStreamTimeouts,
  evaluateExecAllowlist,
  evaluateShellAllowlist,
  expandHomePrefix,
  extractErrorCode,
  fetchWithRuntimeDispatcher,
  fetchWithSsrFGuard,
  fetchWithTimeout,
  findExistingAncestor,
  forceResetGlobalDispatcher,
  formatApprovalDisplayPath,
  formatDurationCompact,
  formatDurationHuman,
  formatDurationPrecise,
  formatDurationSeconds,
  formatErrorMessage,
  formatExecApprovalExpiresIn,
  formatUncaughtError,
  generateSecureFraction,
  generateSecureHex,
  generateSecureInt,
  generateSecureToken,
  generateSecureUuid,
  getChannelActivity,
  getExecApprovalApproverDmNoticeText,
  getExecApprovalReplyMetadata,
  getLastHeartbeatEvent,
  getProxyUrlFromFetch,
  hasDurableExecApproval,
  hasEncodedFileUrlSeparator,
  hasEnvHttpProxyAgentConfigured,
  hasEnvHttpProxyConfigured,
  hasErrnoCode,
  hasLegacyFlatAllowPrivateNetworkAlias,
  hasProxyEnvConfigured,
  hasSystemEvents,
  hasSystemMark,
  installRequestBodyLimitGuard,
  isBlockedHostname,
  isBlockedHostnameOrIp,
  isDiagnosticFlagEnabled,
  isDiagnosticsEnabled,
  isErrno,
  isExecApprovalChannelRuntimeTerminalStartError,
  isExecApprovalDecisionAllowed,
  isHeartbeatEnabledForAgent,
  isHostnameAllowedByPattern,
  isHttpsUrlAllowedByHostnameSuffixAllowlist,
  isPathInside,
  isPrivateIpAddress,
  isPrivateNetworkAllowedByPolicy,
  isPrivateNetworkOptInEnabled,
  isRequestBodyLimitError,
  isSafeBinUsage,
  isSafeScpRemoteHost,
  isSafeScpRemotePath,
  isSameSsrFPolicy,
  isSystemEventContextChanged,
  isTruthyEnvValue,
  isVitestRuntimeEnv,
  isWSL,
  isWSL2Sync,
  isWSLEnv,
  isWSLSync,
  isWindowsNetworkPath,
  isWindowsPlatform,
  loadExecApprovals,
  loadSecretFileSync,
  logAcceptedEnvOption,
  makeProxyFetch,
  matchAllowlist,
  matchesDiagnosticFlag,
  matchesHostnameAllowlist,
  matchesNoProxy,
  maxAsk,
  mergeExecApprovalsSocketDefaults,
  mergeSsrFPolicies,
  migrateLegacyFlatAllowPrivateNetworkAlias,
  minSecurity,
  normalizeEnv,
  normalizeExecApprovals,
  normalizeExecAsk,
  normalizeExecHost,
  normalizeExecSecurity,
  normalizeExecTarget,
  normalizeHostname,
  normalizeHostnameAllowlist,
  normalizeHostnameSuffixAllowlist,
  normalizeOutboundIdentity,
  normalizeSafeBins,
  normalizeScpRemoteHost,
  normalizeScpRemotePath,
  normalizeZaiEnv,
  onDiagnosticEvent,
  onHeartbeatEvent,
  openLocalFileSafely,
  parseExecApprovalCommandText,
  parseExecArgvToken,
  parseFiniteNumber,
  parseStrictInteger,
  parseStrictNonNegativeInteger,
  parseStrictPositiveInteger,
  pathExists,
  pathExistsSync,
  peekSystemEventEntries,
  peekSystemEvents,
  persistAllowAlwaysPatterns,
  prefixSystemMessage,
  pruneMapToMaxSize,
  readJsonIfExists as readDurableJsonFile,
  readJsonIfExists,
  readErrorName,
  readExecApprovalsSnapshot,
  readFileWithinRoot,
  readJson,
  readJson as readJsonFileStrict,
  readJsonBodyWithLimit,
  tryReadJson as readJsonFile,
  tryReadJson,
  tryReadJsonSync as readJsonFileSync,
  tryReadJsonSync,
  readJsonSync,
  readLocalFileFromRoots,
  readLocalFileSafely,
  readRegularFile,
  readRegularFileSync,
  readRequestBodyWithLimit,
  readRootJsonObjectSync,
  readRootJsonSync,
  readRootStructuredFileSync,
  readSecretFileSync,
  readSecureFile,
  recordAllowlistMatchesUse,
  recordAllowlistUse,
  recordChannelActivity,
  requestBodyErrorToText,
  requestExecApprovalViaSocket,
  requireValidExecTarget,
  requiresExecApproval,
  resetChannelActivityForTest,
  resetFileLockStateForTest,
  resetGlobalUndiciStreamTimeoutsForTests,
  resetHeartbeatEventsForTest,
  resetSystemEventsForTest,
  resetWSLStateForTests,
  resolveAbsolutePathForRead,
  resolveAbsolutePathForWrite,
  resolveAgentOutboundIdentity,
  resolveAllowAlwaysPatternEntries,
  resolveAllowAlwaysPatterns,
  resolveAllowlistCandidatePath,
  resolveApprovalAuditCandidatePath,
  resolveApprovalRequestOriginTarget,
  resolveApprovalRequestSessionConversation,
  resolveApprovalRequestSessionTarget,
  resolveChannelNativeApprovalDeliveryPlan,
  resolveCommandResolution,
  resolveCommandResolutionFromArgv,
  resolveDiagnosticFlags,
  resolveEffectiveHomeDir,
  resolveEnvHttpProxyAgentOptions,
  resolveEnvHttpProxyUrl,
  resolveExecApprovalAllowedDecisions,
  resolveExecApprovalCommandDisplay,
  resolveExecApprovalRequestAllowedDecisions,
  resolveExecApprovalSessionTarget,
  resolveExecApprovals,
  resolveExecApprovalsFromFile,
  resolveExecApprovalsPath,
  resolveExecApprovalsSocketPath,
  resolveExecutionTargetCandidatePath,
  resolveExecutionTargetResolution,
  resolveFetch,
  resolveGlobalDedupeCache,
  resolveHeartbeatIntervalMs,
  resolveHeartbeatSummaryForAgent,
  resolveHeartbeatVisibility,
  resolveHomeRelativePath,
  resolveIndicatorType,
  resolveLegacyOutboundSendDepKeys,
  resolveLocalPathFromRootsSync,
  resolveOpenedFileRealPathForHandle,
  resolveOsHomeDir,
  resolveOsHomeRelativePath,
  resolveOutboundSendDep,
  resolvePinnedHostname,
  resolvePinnedHostnameWithPolicy,
  resolvePlannedSegmentArgv,
  resolvePluginApprovalRequestAllowedDecisions,
  resolvePolicyAllowlistCandidatePath,
  resolvePolicyTargetCandidatePath,
  resolvePolicyTargetResolution,
  resolvePreferredOpenClawTmpDir,
  resolveProxyFetchFromEnv,
  resolveRegularFileAppendFlags,
  resolveRequiredHomeDir,
  resolveRequiredOsHomeDir,
  resolveRetryConfig,
  resolveSafeBins,
  resolveSystemEventDeliveryContext,
  resolveUserPath,
  restoreExecApprovalsSnapshot,
  retainSafeHeadersForCrossOriginRedirectHeaders,
  retryAsync,
  root,
  runTasksWithConcurrency,
  safeFileURLToPath,
  sanitizeExecApprovalDisplayText,
  sanitizeExecApprovalWarningText,
  sanitizeForPlainText,
  sanitizeUntrustedFileName,
  saveExecApprovals,
  shouldUseEnvHttpProxyForUrl,
  sleepWithAbort,
  splitCommandChain,
  splitCommandChainWithOperators,
  ssrfPolicyFromAllowPrivateNetwork,
  ssrfPolicyFromDangerouslyAllowPrivateNetwork,
  ssrfPolicyFromHttpBaseUrlAllowedHostname,
  ssrfPolicyFromHttpBaseUrlFakeIpHostnameAllowlist,
  ssrfPolicyFromPrivateNetworkOptIn,
  statRegularFileSync,
  stripInternalRuntimeScaffolding,
  tryReadSecretFileSync,
  trySafeFileURLToPath,
  waitForTransportReady,
  walkDirectory,
  walkDirectorySync,
  windowsEscapeArg,
  withFileLock,
  withStrictGuardedFetchMode,
  withTimeout,
  withTrustedEnvProxyGuardedFetchMode,
  withTrustedExplicitProxyGuardedFetchMode,
  wrapFetchWithAbortSignal,
  writeExternalFileWithinRoot,
  writeFileWithinRoot,
  writeJson,
  writeJson as writeJsonAtomic,
  writeJsonSync,
  writeSecretFileAtomic as writePrivateSecretFileAtomic,
  writeTextAtomic,
};
