import {
  i as resolveAccessGroupAllowFromMatches,
  n as expandAllowFromWithAccessGroups,
  r as parseAccessGroupAllowFromEntry,
  t as ACCESS_GROUP_ALLOW_FROM_PREFIX,
} from "../access-groups-DtHOJBzi.js";
import {
  a as getChannelSurface,
  c as normalizeSecretStringValue,
  i as getChannelRecord,
  l as resolveChannelAccountSurface,
  n as collectNestedChannelFieldAssignments,
  o as hasConfiguredSecretInputValue,
  r as collectSimpleChannelFieldAssignments,
  s as isBaseFieldActiveForChannelSurface,
  t as collectConditionalChannelFieldAssignments,
} from "../channel-secret-basic-runtime-CKc1fA23.js";
import { t as collectNestedChannelTtsAssignments } from "../channel-secret-tts-runtime-CM8Ig1Gt.js";
import {
  n as filterSupplementalContextItems,
  r as shouldIncludeSupplementalContext,
  t as evaluateSupplementalContextVisibility,
} from "../context-visibility-2FK_0ypA.js";
import {
  a as resolveDmGroupAccessWithCommandGate,
  c as resolveOpenDmAllowlistAccess,
  i as resolveDmGroupAccessDecision,
  l as resolvePinnedMainDmOwnerFromAllowlist,
  n as readStoreAllowFromForDmPolicy,
  o as resolveDmGroupAccessWithLists,
  r as resolveDmAllowState,
  s as resolveEffectiveAllowFromLists,
  t as DM_GROUP_ACCESS_REASON,
} from "../dm-policy-shared-COpbJNwP.js";
import { a as formatErrorMessage, i as extractErrorCode } from "../errors-DZMrVkYL.js";
import {
  a as wrapWebContent,
  c as resolveHookExternalContentSource,
  i as wrapExternalContent,
  n as detectSuspiciousPatterns,
  o as isExternalHookSession,
  r as getHookType,
  s as mapHookExternalContentSource,
  t as buildSafeExternalPrompt,
} from "../external-content-BCW9yxs8.js";
import {
  A as findExistingAncestor,
  D as sanitizeUntrustedFileName,
  E as pathExistsSync,
  M as resolveAbsolutePathForWrite,
  O as assertAbsolutePathInput,
  T as pathExists,
  c as writeSiblingTempFile,
  d as pathScope,
  f as resolveExistingPathsWithinRoot,
  g as resolveWritablePathWithinRoot,
  h as resolveStrictExistingPathsWithinRoot,
  j as resolveAbsolutePathForRead,
  k as canonicalPathFromExistingAncestor,
  l as writeViaSiblingTempPath,
  m as resolvePathsWithinRoot,
  p as resolvePathWithinRoot,
  r as writeExternalFileWithinRoot,
  t as ensureAbsoluteDirectory,
  u as withTimeout,
  v as resolveLocalPathFromRootsSync,
} from "../fs-safe-CgBWiL92.js";
import { t as normalizeHostname } from "../hostname-DOneeF6p.js";
import { i as isPathInside, p as FsSafeError, r as isNotFoundPathError } from "../path-1liOXr_N.js";
import { r as ensurePortAvailable } from "../ports-CzR_dSOf.js";
import {
  n as privateFileStoreSync,
  t as privateFileStore,
} from "../private-file-store-Bi7hPs_Y.js";
import { i as hasProxyEnvConfigured } from "../proxy-env-C3VNcjQ7.js";
import {
  d as compileSafeRegex,
  f as compileSafeRegexDetailed,
  i as redactSensitiveText,
  m as testRegexWithBoundedInput,
  p as hasNestedRepetition,
} from "../redact-Mxj55RzQ.js";
import {
  a as resolveRegularFileAppendFlags,
  c as assertNoSymlinkParents,
  i as readRegularFileSync,
  l as assertNoSymlinkParentsSync,
  n as appendRegularFileSync,
  r as readRegularFile,
  s as statRegularFileSync,
  t as appendRegularFile,
} from "../regular-file-CoVHB-2u.js";
import {
  n as replaceFileAtomic,
  r as replaceFileAtomicSync,
  t as movePathWithCopyFallback,
} from "../replace-file-8cLr_oo0.js";
import {
  a as isChannelAccountEffectivelyEnabled,
  c as pushInactiveSurfaceWarning,
  i as hasOwnProperty,
  l as pushWarning,
  n as collectSecretInputAssignment,
  o as isEnabledFlag,
  r as createResolverContext,
  s as pushAssignment,
  t as applyResolvedAssignments,
} from "../runtime-shared-leW4XjHk.js";
import { t as safeEqualSecret } from "../secret-equal-szksNvjy.js";
import { i as generateSecureToken } from "../secure-random-Ck_jpq4r.js";
import { o as root, r as openLocalFileSafely } from "../secure-temp-dir-CCj3cY2B.js";
import {
  n as writeFileFromPathWithinRoot,
  r as buildUntrustedChannelMetadata,
  t as openFileWithinRoot,
} from "../security-runtime-6Bn2Pszp.js";
import {
  a as parseEnvValue,
  c as writeJsonFileSecure,
  i as parseDotPath,
  l as writeTextFileAtomic,
  n as isNonEmptyString,
  o as readTextFileIfExists,
  r as normalizePositiveInt,
  s as toDotPath,
  t as ensureDirForFile,
} from "../shared-Dp_cRzjX.js";
import {
  c as isBlockedHostnameOrIp,
  d as isPrivateNetworkAllowedByPolicy,
  g as resolvePinnedHostnameWithPolicy,
  p as matchesHostnameAllowlist,
  t as SsrFBlockedError,
} from "../ssrf-DO8eIXaD.js";
import { n as resolvePreferredOpenClawTmpDir } from "../tmp-openclaw-dir-B4r8YQhH.js";
import { c as isRecord } from "../utils-BGRcpLKt.js";
export {
  ACCESS_GROUP_ALLOW_FROM_PREFIX,
  DM_GROUP_ACCESS_REASON,
  FsSafeError,
  FsSafeError as SafeOpenError,
  SsrFBlockedError,
  appendRegularFile,
  appendRegularFileSync,
  applyResolvedAssignments,
  assertAbsolutePathInput,
  assertNoSymlinkParents,
  assertNoSymlinkParentsSync,
  buildSafeExternalPrompt,
  buildUntrustedChannelMetadata,
  canonicalPathFromExistingAncestor,
  collectConditionalChannelFieldAssignments,
  collectNestedChannelFieldAssignments,
  collectNestedChannelTtsAssignments,
  collectSecretInputAssignment,
  collectSimpleChannelFieldAssignments,
  compileSafeRegex,
  compileSafeRegexDetailed,
  createResolverContext,
  detectSuspiciousPatterns,
  ensureAbsoluteDirectory,
  ensureDirForFile,
  ensurePortAvailable,
  evaluateSupplementalContextVisibility,
  expandAllowFromWithAccessGroups,
  extractErrorCode,
  filterSupplementalContextItems,
  findExistingAncestor,
  formatErrorMessage,
  generateSecureToken,
  getChannelRecord,
  getChannelSurface,
  getHookType,
  hasConfiguredSecretInputValue,
  hasNestedRepetition,
  hasOwnProperty,
  hasProxyEnvConfigured,
  isBaseFieldActiveForChannelSurface,
  isBlockedHostnameOrIp,
  isChannelAccountEffectivelyEnabled,
  isEnabledFlag,
  isExternalHookSession,
  isNonEmptyString,
  isNotFoundPathError,
  isPathInside,
  isPrivateNetworkAllowedByPolicy,
  isRecord,
  mapHookExternalContentSource,
  matchesHostnameAllowlist,
  movePathWithCopyFallback,
  normalizeHostname,
  normalizePositiveInt,
  normalizeSecretStringValue,
  openFileWithinRoot,
  openLocalFileSafely,
  parseAccessGroupAllowFromEntry,
  parseDotPath,
  parseEnvValue,
  pathExists,
  pathExistsSync,
  pathScope,
  privateFileStore,
  privateFileStoreSync,
  pushAssignment,
  pushInactiveSurfaceWarning,
  pushWarning,
  readRegularFile,
  readRegularFileSync,
  readStoreAllowFromForDmPolicy,
  readTextFileIfExists,
  redactSensitiveText,
  replaceFileAtomic,
  replaceFileAtomicSync,
  resolveAbsolutePathForRead,
  resolveAbsolutePathForWrite,
  resolveAccessGroupAllowFromMatches,
  resolveChannelAccountSurface,
  resolveDmAllowState,
  resolveDmGroupAccessDecision,
  resolveDmGroupAccessWithCommandGate,
  resolveDmGroupAccessWithLists,
  resolveEffectiveAllowFromLists,
  resolveExistingPathsWithinRoot,
  resolveHookExternalContentSource,
  resolveLocalPathFromRootsSync,
  resolveOpenDmAllowlistAccess,
  resolvePathWithinRoot,
  resolvePathsWithinRoot,
  resolvePinnedHostnameWithPolicy,
  resolvePinnedMainDmOwnerFromAllowlist,
  resolvePreferredOpenClawTmpDir,
  resolveRegularFileAppendFlags,
  resolveStrictExistingPathsWithinRoot,
  resolveWritablePathWithinRoot,
  root,
  safeEqualSecret,
  sanitizeUntrustedFileName,
  shouldIncludeSupplementalContext,
  statRegularFileSync,
  testRegexWithBoundedInput,
  toDotPath,
  withTimeout,
  wrapExternalContent,
  wrapWebContent,
  writeExternalFileWithinRoot,
  writeFileFromPathWithinRoot,
  writeJsonFileSecure,
  writeSiblingTempFile,
  writeTextFileAtomic,
  writeViaSiblingTempPath,
};
